runtime: nodejs18

handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301

env_variables:
  NODE_ENV: "production"
  
automatic_scaling:
  min_instances: 1
  max_instances: 100
  
resources:
  cpu: 2
  memory_gb: 2
  disk_size_gb: 10