steps:
  # Install dependencies using Node 20 to avoid npm version issues
  - name: 'node:20'
    entrypoint: npm  
    args: ['install', '--legacy-peer-deps', '--no-audit', '--no-fund']
    env:
      - 'NPM_CONFIG_LOGLEVEL=warn'
      - 'NPM_CONFIG_PROGRESS=false'
      - 'NODE_ENV=production'
    
  # Build the Next.js application  
  - name: 'node:20'
    entrypoint: npm
    args: ['run', 'build']
    env:
      - 'NODE_ENV=production'
      - 'NEXT_TELEMETRY_DISABLED=1'
      - 'GENERATE_SOURCEMAP=false'
      
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/isectech-app',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/isectech-app:$COMMIT_SHA',
      '-f', 'Dockerfile.frontend.production',
      '.'
    ]
    
  # Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/isectech-app']

# Deploy to Cloud Run
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/isectech-app'
  
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  substitution_option: 'ALLOW_LOOSE'
  
timeout: '1800s'