steps:
  # Install dependencies
  - name: 'node:18'
    entrypoint: npm
    args: ['ci', '--production=false', '--legacy-peer-deps']
    
  # Build the Next.js application
  - name: 'node:18'
    entrypoint: npm
    args: ['run', 'build']
    env:
      - 'NODE_ENV=production'
      - 'NEXT_TELEMETRY_DISABLED=1'
      
  # Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/isectech-app',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/isectech-app:$COMMIT_SHA',
      '-f', 'Dockerfile.frontend.production',
      '.'
    ]
    
  # Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '--all-tags', 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/isectech-app']

# Deploy to Cloud Run
images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloud-run-source-deploy/isectech-app'
  
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
  
timeout: '1200s'