# iSECTECH Frontend - Cloud Run Deployment Configuration
# Author: Claude Code - iSECTECH Infrastructure Team
# Version: 2.0.0

apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: isectech-frontend
  namespace: default
  labels:
    app: isectech-frontend
    tier: presentation
    component: web-application
    version: "2.0.0"
    environment: production
    managed-by: isectech-platform
  annotations:
    # Cloud Run specific annotations
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/launch-stage: GA
    
    # IAM annotations
    run.googleapis.com/invoker: allUsers
    
    # Binary authorization
    run.googleapis.com/binary-authorization-policy: default
    
    # VPC connector for private networking
    run.googleapis.com/vpc-access-connector: isectech-vpc-connector
    run.googleapis.com/vpc-access-egress: private-ranges-only
    
    # Custom domain
    run.googleapis.com/custom-audiences: protect.isectech.com
    
    # Revision naming
    run.googleapis.com/revision-suffix: "frontend-v2-0-0"
    
    # Traffic allocation
    run.googleapis.com/rollout-policy: gradual
    
    # Security
    run.googleapis.com/secure-headers: true
    
    # Monitoring
    run.googleapis.com/cpu-throttling: false
    run.googleapis.com/enable-audit-logs: true
    
spec:
  template:
    metadata:
      labels:
        app: isectech-frontend
        version: "2.0.0"
        tier: presentation
      annotations:
        # Resource allocation
        run.googleapis.com/memory: "1Gi"
        run.googleapis.com/cpu: "1000m"
        
        # Scaling configuration
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "100"
        
        # Concurrency settings
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/max-instances: "100"
        run.googleapis.com/min-instances: "1"
        
        # Timeout and startup
        run.googleapis.com/timeout: "300s"
        run.googleapis.com/startup-probe-timeout: "240s"
        
        # Security context
        run.googleapis.com/sandbox: gvisor
        
        # Secrets manager integration (comprehensive)
        run.googleapis.com/secrets: |
          NEXTAUTH_SECRET:isectech-nextauth-secret:latest,
          GOOGLE_CLIENT_SECRET:isectech-google-oauth-client-secret:latest,
          MICROSOFT_CLIENT_SECRET:isectech-microsoft-oauth-client-secret:latest,
          OKTA_CLIENT_SECRET:isectech-okta-oauth-client-secret:latest,
          SESSION_ENCRYPTION_KEY:isectech-session-encryption-key:latest,
          GOOGLE_MAPS_API_KEY:isectech-google-maps-api-key:latest,
          MAPBOX_ACCESS_TOKEN:isectech-mapbox-access-token:latest
        
        # Service account
        run.googleapis.com/service-account: isectech-frontend-sa@isectech-security-platform.iam.gserviceaccount.com
        
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      
      containers:
      - name: isectech-frontend
        image: us-central1-docker.pkg.dev/isectech-security-platform/isectech-production/frontend:latest
        
        # Resource limits and requests
        resources:
          limits:
            memory: "1Gi"
            cpu: "1000m"
          requests:
            memory: "512Mi"
            cpu: "500m"
        
        # Port configuration
        ports:
        - name: http1
          containerPort: 3000
          protocol: TCP
        
        # Environment variables
        env:
        # Application Configuration
        - name: NODE_ENV
          value: "production"
        - name: NEXT_TELEMETRY_DISABLED
          value: "1"
        - name: SERVICE_NAME
          value: "isectech-frontend"
        - name: SERVICE_VERSION
          value: "2.0.0"
        - name: ENVIRONMENT
          value: "production"
        
        # Network Configuration
        - name: PORT
          value: "3000"
        - name: HOSTNAME
          value: "0.0.0.0"
        
        # API Endpoints
        - name: NEXT_PUBLIC_API_URL
          value: "https://api.isectech.com"
        - name: NEXT_PUBLIC_API_GATEWAY_URL
          value: "https://gateway.isectech.com"
        - name: NEXT_PUBLIC_WS_URL
          value: "wss://ws.isectech.com"
        
        # Authentication Configuration
        - name: NEXTAUTH_URL
          value: "https://protect.isectech.com"
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: isectech-nextauth-secret
              key: latest
        
        # OAuth Configuration (from Secret Manager)
        - name: GOOGLE_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: isectech-google-oauth-client-id
              key: latest
        - name: GOOGLE_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: isectech-google-oauth-client-secret
              key: latest
        - name: MICROSOFT_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: isectech-microsoft-oauth-client-id
              key: latest
        - name: MICROSOFT_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: isectech-microsoft-oauth-client-secret
              key: latest
        - name: OKTA_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: isectech-okta-oauth-client-id
              key: latest
        - name: OKTA_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: isectech-okta-oauth-client-secret
              key: latest
        - name: OKTA_ISSUER
          valueFrom:
            secretKeyRef:
              name: isectech-okta-issuer
              key: latest
        
        # Session and Security Keys (from Secret Manager)
        - name: SESSION_ENCRYPTION_KEY
          valueFrom:
            secretKeyRef:
              name: isectech-session-encryption-key
              key: latest
        
        # Third-party API Keys (from Secret Manager)
        - name: NEXT_PUBLIC_GOOGLE_MAPS_API_KEY
          valueFrom:
            secretKeyRef:
              name: isectech-google-maps-api-key
              key: latest
        - name: NEXT_PUBLIC_MAPBOX_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: isectech-mapbox-access-token
              key: latest
        
        # Security Configuration
        - name: SECURITY_HEADERS_ENABLED
          value: "true"
        - name: CSP_ENABLED
          value: "true"
        - name: HSTS_ENABLED
          value: "true"
        - name: SECURE_COOKIES
          value: "true"
        
        # CORS Configuration
        - name: CORS_ENABLED
          value: "true"
        - name: CORS_ORIGIN
          value: "https://protect.isectech.com"
        
        # Feature Flags
        - name: NEXT_PUBLIC_FEATURE_DARK_MODE
          value: "true"
        - name: NEXT_PUBLIC_FEATURE_NOTIFICATIONS
          value: "true"
        - name: NEXT_PUBLIC_FEATURE_REAL_TIME
          value: "true"
        - name: NEXT_PUBLIC_FEATURE_ANALYTICS
          value: "true"
        - name: NEXT_PUBLIC_FEATURE_MULTI_TENANT
          value: "true"
        - name: NEXT_PUBLIC_FEATURE_MFA
          value: "true"
        - name: NEXT_PUBLIC_FEATURE_SSO
          value: "true"
        
        # CDN and Assets
        - name: NEXT_PUBLIC_CDN_URL
          value: "https://cdn.isectech.com"
        - name: NEXT_PUBLIC_ASSETS_URL
          value: "https://assets.isectech.com"
        
        # Session Configuration
        - name: SESSION_TIMEOUT
          value: "28800"
        - name: SESSION_ABSOLUTE_TIMEOUT
          value: "86400"
        - name: IDLE_TIMEOUT
          value: "3600"
        
        # Rate Limiting
        - name: RATE_LIMIT_ENABLED
          value: "true"
        - name: RATE_LIMIT_MAX
          value: "100"
        - name: RATE_LIMIT_WINDOW
          value: "900"
        
        # Performance Monitoring
        - name: PERFORMANCE_MONITORING
          value: "true"
        - name: SENTRY_ENABLED
          value: "false"
        - name: ANALYTICS_ENABLED
          value: "false"
        
        # Logging Configuration
        - name: LOG_LEVEL
          value: "info"
        - name: LOG_FORMAT
          value: "json"
        - name: ACCESS_LOG_ENABLED
          value: "true"
        - name: ERROR_LOG_ENABLED
          value: "true"
        
        # Health and Monitoring
        - name: HEALTH_CHECK_ENABLED
          value: "true"
        - name: METRICS_ENABLED
          value: "true"
        - name: TRACING_ENABLED
          value: "false"
        
        # Contact Information
        - name: NEXT_PUBLIC_SUPPORT_EMAIL
          value: "support@isectech.com"
        - name: NEXT_PUBLIC_SECURITY_EMAIL
          value: "security@isectech.com"
        
        # Build Information (populated by CI/CD)
        - name: NEXT_PUBLIC_BUILD_DATE
          value: "2024-01-01T00:00:00Z"
        - name: NEXT_PUBLIC_BUILD_VERSION
          value: "2.0.0"
        - name: NEXT_PUBLIC_BUILD_COMMIT
          value: "latest"
        
        # Health checks
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
            httpHeaders:
            - name: User-Agent
              value: "GoogleHC/1.0"
          initialDelaySeconds: 15
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
          successThreshold: 1
        
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
            httpHeaders:
            - name: User-Agent
              value: "GoogleHC/1.0"
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
          successThreshold: 1
        
        startupProbe:
          httpGet:
            path: /api/health
            port: 3000
            httpHeaders:
            - name: User-Agent
              value: "GoogleHC/1.0"
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 48
          successThreshold: 1
        
        # Security Context
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          runAsGroup: 10001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
        
        # Volume mounts (if needed)
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: var-log
          mountPath: /var/log
      
      # Volumes
      volumes:
      - name: tmp
        emptyDir: {}
      - name: var-log
        emptyDir: {}
      
      # Service account
      serviceAccountName: isectech-frontend-sa

---
# Traffic configuration for gradual rollout
apiVersion: serving.knative.dev/v1
kind: Configuration
metadata:
  name: isectech-frontend-config
  namespace: default
spec:
  template:
    metadata:
      annotations:
        # Revision specific configuration
        run.googleapis.com/revision-timeout: "300s"
        run.googleapis.com/memory: "1Gi"
        run.googleapis.com/cpu: "1000m"

---
# Custom domain mapping
apiVersion: serving.knative.dev/v1alpha1
kind: DomainMapping
metadata:
  name: protect.isectech.com
  namespace: default
  labels:
    app: isectech-frontend
spec:
  ref:
    name: isectech-frontend
    kind: Service
    apiVersion: serving.knative.dev/v1
  certificateMode: AUTOMATIC
  forceOverride: true

---
# IAM Policy for the frontend service
apiVersion: v1
kind: ServiceAccount
metadata:
  name: isectech-frontend-sa
  namespace: default
  labels:
    app: isectech-frontend
  annotations:
    iam.gke.io/gcp-service-account: isectech-frontend-sa@isectech-security-platform.iam.gserviceaccount.com

---
# Monitoring configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: isectech-frontend-monitoring
  namespace: default
  labels:
    app: isectech-frontend
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
    - job_name: 'isectech-frontend'
      static_configs:
      - targets: ['isectech-frontend:3000']
      metrics_path: '/api/metrics'
      scrape_interval: 30s
      scrape_timeout: 10s