# iSECTECH Network Security Monitoring - Suricata Configuration
# Production-grade intrusion detection and prevention system

# ═══════════════════════════════════════════════════════════════════════════════
# VARIABLES AND NETWORK CONFIGURATION
# ═══════════════════════════════════════════════════════════════════════════════

vars:
  address-groups:
    HOME_NET: "[192.168.0.0/16,10.0.0.0/8,172.16.0.0/12]"
    EXTERNAL_NET: "!$HOME_NET"
    
    # HTTP servers
    HTTP_SERVERS: "$HOME_NET"
    SMTP_SERVERS: "$HOME_NET"
    SQL_SERVERS: "$HOME_NET"
    DNS_SERVERS: "$HOME_NET"
    TELNET_SERVERS: "$HOME_NET"
    AIM_SERVERS: "$EXTERNAL_NET"
    DC_SERVERS: "$HOME_NET"
    DNP3_SERVER: "$HOME_NET"
    DNP3_CLIENT: "$HOME_NET"
    MODBUS_CLIENT: "$HOME_NET"
    MODBUS_SERVER: "$HOME_NET"
    ENIP_CLIENT: "$HOME_NET"
    ENIP_SERVER: "$HOME_NET"

  port-groups:
    HTTP_PORTS: "80"
    SHELLCODE_PORTS: "!80"
    ORACLE_PORTS: 1521
    SSH_PORTS: 22
    DNP3_PORTS: 20000
    MODBUS_PORTS: 502
    FILE_DATA_PORTS: "[$HTTP_PORTS,110,143]"
    FTP_PORTS: 21
    VXWORKS_PORTS: 17185
    TEREDO_PORTS: 3544

# ═══════════════════════════════════════════════════════════════════════════════
# DEFAULT RULE ACTION
# ═══════════════════════════════════════════════════════════════════════════════

default-rule-path: /var/lib/suricata/rules
rule-files:
  - suricata.rules
  - isectech-custom.rules
  - emerging-threats.rules
  - malware.rules
  - botcc.rules
  - compromised.rules
  - drop.rules
  - dshield.rules
  - tor.rules
  - emerging-dns.rules
  - emerging-dos.rules
  - emerging-exploit.rules
  - emerging-ftp.rules
  - emerging-imap.rules
  - emerging-malware.rules
  - emerging-mobile_malware.rules
  - emerging-netbios.rules
  - emerging-p2p.rules
  - emerging-policy.rules
  - emerging-pop3.rules
  - emerging-rpc.rules
  - emerging-scada.rules
  - emerging-scan.rules
  - emerging-shellcode.rules
  - emerging-smtp.rules
  - emerging-snmp.rules
  - emerging-sql.rules
  - emerging-telnet.rules
  - emerging-tftp.rules
  - emerging-trojan.rules
  - emerging-user_agents.rules
  - emerging-voip.rules
  - emerging-web_client.rules
  - emerging-web_server.rules
  - emerging-web_specific_apps.rules
  - emerging-worm.rules

classification-file: /etc/suricata/classification.config
reference-config-file: /etc/suricata/reference.config

# ═══════════════════════════════════════════════════════════════════════════════
# LOGGING CONFIGURATION
# ═══════════════════════════════════════════════════════════════════════════════

default-log-dir: /var/log/suricata/

# ═══════════════════════════════════════════════════════════════════════════════
# GLOBAL CONFIGURATION
# ═══════════════════════════════════════════════════════════════════════════════

# Global stats configuration
stats:
  enabled: yes
  interval: 60

# ═══════════════════════════════════════════════════════════════════════════════
# OUTPUT CONFIGURATION
# ═══════════════════════════════════════════════════════════════════════════════

outputs:
  - console:
      enabled: no
  
  # EVE JSON log for SIEM integration
  - eve-log:
      enabled: yes
      filetype: regular
      filename: eve.json
      community-id: yes
      community-id-seed: 0
      types:
        - alert:
            payload: yes
            payload-buffer-size: 4kb
            payload-printable: yes
            packet: yes
            metadata: yes
            tagged-packets: yes
            xff:
              enabled: yes
              mode: extra-data
              deployment: reverse
              header: X-Forwarded-For
        - anomaly:
            enabled: yes
            types:
              # decode: yes
              # stream: yes
              # applayer: yes
        - http:
            enabled: yes
            extended: yes
            custom: [Accept, Accept-Charset, Accept-Encoding, Accept-Language, Accept-Datetime, Authorization, Cache-Control, Cookie, From, Max-Forwards, Origin, Pragma, Proxy-Authorization, Range, TE, VIA, X-Requested-With, DNT, X-Forwarded-Proto, Accept-Range, Age, Allow, Connection, Content-Encoding, Content-Language, Content-Length, Content-Location, Content-MD5, Content-Range, Content-Type, Date, ETag, Expires, Last-Modified, Link, Location, Proxy-Authenticate, Referrer, Refresh, Retry-After, Server, Set-Cookie, Trailer, Transfer-Encoding, Upgrade, Vary, Warning, WWW-Authenticate, X-Flash-Version, X-Forwarded-Proto, X-Authenticated-User]
        - dns:
            enabled: yes
            version: 2
        - tls:
            enabled: yes
            extended: yes
        - files:
            enabled: yes
            force-magic: yes
            force-hash: [md5, sha1, sha256]
        - smtp:
            enabled: yes
            extended: yes
        - ssh:
            enabled: yes
        - stats:
            enabled: yes
            totals: yes
            threads: yes
            deltas: yes
        - flow:
            enabled: yes
        - netflow:
            enabled: yes
        - nfs:
            enabled: yes
            version: 2
        - smb:
            enabled: yes
            version: 2
        - krb5:
            enabled: yes
        - snmp:
            enabled: yes
        - sip:
            enabled: yes
        - dhcp:
            enabled: yes
            extended: yes
        - rfb:
            enabled: yes
        - mqtt:
            enabled: yes
        - http2:
            enabled: yes
        - pgsql:
            enabled: yes
        - ike:
            enabled: yes
            version: 2

  # Fast log for high-performance alerting
  - fast:
      enabled: yes
      filename: fast.log
      append: yes

  # Unified2 format for legacy tool compatibility
  - unified2-alert:
      enabled: no
      filename: unified2.alert

  # HTTP transaction logging
  - http-log:
      enabled: yes
      filename: http.log
      append: yes

  # TLS handshake logging
  - tls-log:
      enabled: yes
      filename: tls.log
      append: yes
      extended: yes

  # DNS transaction logging
  - dns-log:
      enabled: yes
      filename: dns.log
      append: yes

  # Packet capture for detailed analysis
  - pcap-log:
      enabled: no
      filename: log.pcap
      limit: 1000mb
      max-files: 2000

  # Drop logs
  - drop:
      enabled: yes
      filename: drop.log
      append: yes

# ═══════════════════════════════════════════════════════════════════════════════
# PERFORMANCE AND THREADING CONFIGURATION
# ═══════════════════════════════════════════════════════════════════════════════

# Threading configuration for high-performance
threading:
  set-cpu-affinity: yes
  cpu-affinity:
    - management-cpu-set:
        cpu: [ 0 ]
    - receive-cpu-set:
        cpu: [ 1, 2, 3, 4 ]
    - worker-cpu-set:
        cpu: [ 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16 ]
    - verdict-cpu-set:
        cpu: [ 17, 18, 19, 20 ]
  detect-thread-ratio: 1.0

# ═══════════════════════════════════════════════════════════════════════════════
# DETECTION ENGINE CONFIGURATION
# ═══════════════════════════════════════════════════════════════════════════════

detect-engine:
  - profile: high
  - custom-values:
      toclient-groups: 3
      toserver-groups: 25
  - sgh-mpm-context: auto
  - inspection-recursion-limit: 3000
  - prefilter:
      default: mpm
  - grouping:
      tcp-whitelist: 53, 80, 88, 135, 139, 443, 445, 993, 995
      udp-whitelist: 53, 135, 5060

# Multi-pattern algorithm configuration
mpm-algo: hs
pattern-matcher:
  - b2gc:
      search-algo: B2gSearchBNDMq
      hash-size: low
      bf-size: medium
  - b2gm:
      search-algo: B2gSearchBNDMq
      hash-size: low
      bf-size: medium
  - b2g:
      search-algo: B2gSearchBNDMq
      hash-size: low
      bf-size: medium
  - b3g:
      search-algo: B3gSearchBNDMq
      hash-size: low
      bf-size: medium
  - wumanber:
      hash-size: low
      bf-size: medium

# ═══════════════════════════════════════════════════════════════════════════════
# NETWORK INTERFACE CONFIGURATION
# ═══════════════════════════════════════════════════════════════════════════════

af-packet:
  - interface: eth0
    cluster-id: 98
    cluster-type: cluster_flow
    defrag: yes
    use-mmap: yes
    mmap-locked: yes
    tpacket-v3: yes
    ring-size: 2048
    block-size: 1048576
    block-timeout: 10
    use-emergency-flush: yes
  - interface: eth1
    cluster-id: 97
    cluster-type: cluster_flow
    defrag: yes
    use-mmap: yes
    mmap-locked: yes
    tpacket-v3: yes
    ring-size: 2048
    block-size: 1048576
    block-timeout: 10
    use-emergency-flush: yes
  - interface: eth2
    cluster-id: 96
    cluster-type: cluster_flow
    defrag: yes
    use-mmap: yes
    mmap-locked: yes
    tpacket-v3: yes
    ring-size: 2048
    block-size: 1048576
    block-timeout: 10
    use-emergency-flush: yes
  - interface: eth3
    cluster-id: 95
    cluster-type: cluster_flow
    defrag: yes
    use-mmap: yes
    mmap-locked: yes
    tpacket-v3: yes
    ring-size: 2048
    block-size: 1048576
    block-timeout: 10
    use-emergency-flush: yes

# ═══════════════════════════════════════════════════════════════════════════════
# STREAM CONFIGURATION
# ═══════════════════════════════════════════════════════════════════════════════

stream:
  memcap: 64mb
  checksum-validation: yes
  inline: auto
  reassembly:
    memcap: 256mb
    depth: 1mb
    toserver-chunk-size: 2560
    toclient-chunk-size: 2560
    randomize-chunk-size: yes

# ═══════════════════════════════════════════════════════════════════════════════
# FLOW CONFIGURATION
# ═══════════════════════════════════════════════════════════════════════════════

flow:
  memcap: 128mb
  hash-size: 65536
  prealloc: 10000
  emergency-recovery: 30
  managers: 1
  recyclers: 1

# ═══════════════════════════════════════════════════════════════════════════════
# DEFRAGMENTATION CONFIGURATION
# ═══════════════════════════════════════════════════════════════════════════════

defrag:
  memcap: 32mb
  hash-size: 65536
  trackers: 65535
  max-frags: 65535
  prealloc: yes
  timeout: 60

# ═══════════════════════════════════════════════════════════════════════════════
# HOST CONFIGURATION
# ═══════════════════════════════════════════════════════════════════════════════

host:
  hash-size: 4096
  prealloc: 1000
  memcap: 32mb

# ═══════════════════════════════════════════════════════════════════════════════
# APPLICATION LAYER PARSERS
# ═══════════════════════════════════════════════════════════════════════════════

app-layer:
  protocols:
    rfb:
      enabled: yes
      detection-ports:
        dp: 5900, 5901, 5902, 5903, 5904, 5905, 5906, 5907, 5908, 5909
    mqtt:
      enabled: yes
      max-msg-length: 1mb
    krb5:
      enabled: yes
    snmp:
      enabled: yes
    ikev2:
      enabled: yes
    tls:
      enabled: yes
      detection-ports:
        dp: 443, 993, 995, 5061
      ja3-fingerprints: yes
      ja3s-fingerprints: yes
    dcerpc:
      enabled: yes
    ftp:
      enabled: yes
      memcap: 64mb
    rdp:
      enabled: yes
    ssh:
      enabled: yes
    http2:
      enabled: yes
      http2.body-detection: yes
    smtp:
      enabled: yes
      raw-extraction: no
      mime:
        decode-mime: yes
        decode-base64: yes
        decode-quoted-printable: yes
        header-value-depth: 2000
        extract-urls: yes
        body-md5: yes
      inspected-tracker:
        content-limit: 100000
        content-inspect-min-size: 32768
        content-inspect-window: 4096
    imap:
      enabled: detection-only
    msn:
      enabled: detection-only
    smb:
      enabled: yes
      detection-ports:
        dp: 139, 445
    nfs:
      enabled: yes
    tftp:
      enabled: yes
    dns:
      tcp:
        enabled: yes
        detection-ports:
          dp: 53
      udp:
        enabled: yes
        detection-ports:
          dp: 53
    http:
      enabled: yes
      libhtp:
         default-config:
           personality: IDS
           request-body-limit: 100kb
           response-body-limit: 100kb
           request-body-minimal-inspect-size: 32kb
           request-body-inspect-window: 4kb
           response-body-minimal-inspect-size: 40kb
           response-body-inspect-window: 16kb
           response-body-decompress-layer-limit: 2
           http-body-inline: auto
           swf-decompression:
             enabled: yes
             type: both
             compress-depth: 100kb
             decompress-depth: 100kb
           double-decode-path: no
           double-decode-query: no
           response-body-drop-size: 200kb
           request-body-drop-size: 200kb
           max-chunk-size: 8192

# ═══════════════════════════════════════════════════════════════════════════════
# PROTOCOL DETECTION CONFIGURATION
# ═══════════════════════════════════════════════════════════════════════════════

asn1-max-frames: 256

# ═══════════════════════════════════════════════════════════════════════════════
# RULE PROFILING AND PERFORMANCE
# ═══════════════════════════════════════════════════════════════════════════════

profiling:
  rules:
    enabled: yes
    filename: rule_perf.log
    append: yes
    sort: avgticks
    limit: 10
    json: yes
  keywords:
    enabled: yes
    filename: keyword_perf.log
    append: yes
  prefilter:
    enabled: yes
    filename: prefilter_perf.log
    append: yes
  rulegroups:
    enabled: yes
    filename: rule_group_perf.log
    append: yes
  packets:
    enabled: yes
    filename: packet_stats.log
    append: yes
    csv:
      enabled: no
      filename: packet_stats.csv
  locks:
    enabled: no
    filename: lock_stats.log
    append: yes
  pcap-log:
    enabled: no
    filename: pcaplog_stats.log
    append: yes

# ═══════════════════════════════════════════════════════════════════════════════
# COREDUMP CONFIGURATION
# ═══════════════════════════════════════════════════════════════════════════════

coredump:
  max-dump: unlimited

# ═══════════════════════════════════════════════════════════════════════════════
# NAPATECH CONFIGURATION (IF AVAILABLE)
# ═══════════════════════════════════════════════════════════════════════════════

napatech:
  auto-config: yes
  total-processors: 16
  cpu-affinity: 0-15

# ═══════════════════════════════════════════════════════════════════════════════
# UNIX SOCKET CONFIGURATION
# ═══════════════════════════════════════════════════════════════════════════════

unix-command:
  enabled: auto
  filename: suricata-command.socket

# ═══════════════════════════════════════════════════════════════════════════════
# EXCEPTION POLICIES
# ═══════════════════════════════════════════════════════════════════════════════

exception-policy: auto

# ═══════════════════════════════════════════════════════════════════════════════
# PACKET ACQUISITION
# ═══════════════════════════════════════════════════════════════════════════════

pcap:
  - interface: default

pcap-file:
  checksum-checks: auto

# ═══════════════════════════════════════════════════════════════════════════════
# INCLUDE FILES
# ═══════════════════════════════════════════════════════════════════════════════

include: /etc/suricata/threshold.config

# ═══════════════════════════════════════════════════════════════════════════════
# LEGACY SETTINGS
# ═══════════════════════════════════════════════════════════════════════════════

legacy:
  uricontent: enabled