# iSECTECH Vulnerability Correlation and Contextualization Configuration
# Production-grade vulnerability correlation with network monitoring integration

# General Configuration
general:
  # Environment settings
  environment: "production"
  debug_mode: false
  log_level: "INFO"
  
  # Service settings
  service_name: "vulnerability-correlation-engine"
  version: "1.0.0"
  bind_address: "0.0.0.0"
  port: 8447
  
  # Processing intervals
  correlation_interval: 1800  # 30 minutes
  risk_assessment_interval: 3600  # 1 hour
  alert_enrichment_interval: 300  # 5 minutes

# Data Ingestion Configuration
data_ingestion:
  enabled: true
  
  # Vulnerability Scanners
  vulnerability_scanners:
    # Nessus integration
    nessus:
      enabled: true
      connection:
        host: "nessus.isectech.local"
        port: 8834
        access_key: "${NESSUS_ACCESS_KEY}"
        secret_key: "${NESSUS_SECRET_KEY}"
        verify_ssl: true
      
      # Scan retrieval settings
      retrieval:
        auto_download: true
        download_interval: 3600  # 1 hour
        scan_history_days: 30
        include_completed_only: true
        
      # File processing
      file_processing:
        storage_path: "/var/lib/nsm/vulnerability_data/nessus"
        archive_after_processing: true
        archive_retention_days: 90
        parallel_processing: true
        max_concurrent_files: 5
    
    # OpenVAS integration
    openvas:
      enabled: true
      connection:
        host: "openvas.isectech.local"
        port: 9390
        username: "${OPENVAS_USERNAME}"
        password: "${OPENVAS_PASSWORD}"
        protocol: "omp"
      
      # Report retrieval
      retrieval:
        auto_download: true
        download_interval: 3600  # 1 hour
        report_formats: ["xml"]
        include_notes: true
        
      file_processing:
        storage_path: "/var/lib/nsm/vulnerability_data/openvas"
        archive_after_processing: true
        archive_retention_days: 90
    
    # Qualys integration
    qualys:
      enabled: false
      connection:
        api_url: "https://qualysapi.qualys.com"
        username: "${QUALYS_USERNAME}"
        password: "${QUALYS_PASSWORD}"
        
      retrieval:
        auto_download: true
        download_interval: 7200  # 2 hours
        scan_types: ["VULNERABILITY", "COMPLIANCE"]
        
      file_processing:
        storage_path: "/var/lib/nsm/vulnerability_data/qualys"
        format: "csv"
    
    # Custom scanner support
    custom_scanners:
      enabled: true
      
      # File-based input
      file_input:
        enabled: true
        watch_directories:
          - path: "/var/input/nsm/vulnerability_scans"
            file_patterns: ["*.xml", "*.csv", "*.json"]
            recursive: true
            delete_after_processing: false
            
        # File format detection
        format_detection:
          auto_detect: true
          supported_formats:
            - nessus_v2
            - openvas_xml
            - qualys_csv
            - nmap_xml
            - custom_json
  
  # Network Monitoring Integration
  network_monitoring:
    enabled: true
    
    # Asset discovery integration
    asset_discovery:
      enabled: true
      redis_connection:
        host: "redis-nsm.isectech.local"
        port: 6379
        db: 6  # Asset discovery database
        password: "${REDIS_PASSWORD}"
      correlation_window: 3600  # 1 hour
      
    # Flow monitoring integration
    flow_monitoring:
      enabled: true
      data_sources:
        - type: "redis"
          connection: "redis-nsm.isectech.local:6379"
          db: 0
          key_pattern: "flow:*"
          
        - type: "elasticsearch"
          connection: "elastic01.isectech.local:9200"
          index_pattern: "network-flows-*"
          
    # Intrusion detection integration
    ids_integration:
      enabled: true
      suricata:
        enabled: true
        eve_log_path: "/var/log/suricata/eve.json"
        alert_types: ["alert", "anomaly"]
        
      zeek:
        enabled: true
        log_directory: "/var/log/zeek"
        relevant_logs: ["conn.log", "http.log", "ssl.log", "dns.log"]

# Threat Intelligence Correlation
threat_intelligence:
  enabled: true
  update_frequency: 3600  # 1 hour
  
  # CVE Database Integration
  cve_database:
    enabled: true
    
    # National Vulnerability Database
    nvd:
      enabled: true
      api_url: "https://services.nvd.nist.gov/rest/json/cves/2.0"
      api_key: "${NVD_API_KEY}"
      update_frequency: 3600  # 1 hour
      request_delay: 6  # seconds between requests
      
    # MITRE CVE
    mitre:
      enabled: true
      cve_feed_url: "https://cve.mitre.org/data/downloads/allitems.csv"
      update_frequency: 86400  # 24 hours
      
    # Local CVE database
    local_database:
      enabled: true
      database_path: "/var/lib/nsm/cve_database.db"
      cache_size_mb: 256
  
  # Exploit Databases
  exploit_databases:
    enabled: true
    
    # Exploit Database
    exploit_db:
      enabled: true
      api_url: "https://www.exploit-db.com/api/v1"
      download_path: "/var/lib/nsm/exploit_db"
      update_frequency: 86400  # 24 hours
      
    # Metasploit modules
    metasploit:
      enabled: true
      modules_path: "/opt/metasploit-framework/modules"
      update_frequency: 604800  # 7 days
      
    # Custom exploit intelligence
    custom_exploits:
      enabled: true
      sources:
        - type: "file"
          path: "/etc/nsm/threat_intel/custom_exploits.json"
        - type: "api"
          url: "https://ti.isectech.local/api/v1/exploits"
          api_key: "${TI_API_KEY}"
  
  # Threat Actor Intelligence
  threat_actors:
    enabled: true
    
    # MISP integration
    misp:
      enabled: true
      api_url: "https://misp.isectech.local"
      api_key: "${MISP_API_KEY}"
      
    # Custom threat intelligence
    custom_intelligence:
      enabled: true
      sources:
        - type: "file"
          path: "/etc/nsm/threat_intel/threat_actors.json"
        - type: "api"
          url: "https://ti.isectech.local/api/v1/threat-actors"
          api_key: "${TI_API_KEY}"

# Risk Scoring Configuration
risk_scoring:
  enabled: true
  
  # CVSS Integration
  cvss:
    enabled: true
    version_preference: "3.1"  # Prefer CVSS 3.1 over 2.0
    
    # Score weighting
    base_score_weight: 0.4
    temporal_score_weight: 0.3
    environmental_score_weight: 0.3
    
    # Environmental metrics customization
    environmental_metrics:
      modified_attack_vector: "network"
      modified_attack_complexity: "low"
      modified_privileges_required: "none"
      confidentiality_requirement: "high"
      integrity_requirement: "high"
      availability_requirement: "high"
  
  # Exploit Availability Scoring
  exploit_availability:
    enabled: true
    
    # Scoring factors
    factors:
      public_exploit_exists: 3.0
      metasploit_module_exists: 2.5
      proof_of_concept_exists: 2.0
      exploit_complexity_low: 1.5
      weaponization_likely: 2.0
      
    # Age-based decay
    age_decay:
      enabled: true
      half_life_days: 365
      minimum_score: 0.1
  
  # Asset Criticality Integration
  asset_criticality:
    enabled: true
    
    # Criticality sources
    sources:
      asset_discovery: true
      cmdb_integration: false
      manual_classification: true
      
    # Criticality multipliers
    multipliers:
      critical: 3.0
      high: 2.0
      medium: 1.5
      low: 1.0
      unknown: 1.2
      
    # Business impact factors
    business_impact:
      revenue_generating: 2.0
      customer_facing: 1.8
      compliance_required: 1.5
      development_environment: 0.8
  
  # Network Exposure Assessment
  network_exposure:
    enabled: true
    
    # Exposure factors
    factors:
      internet_facing: 2.5
      dmz_located: 2.0
      internal_network: 1.0
      isolated_network: 0.5
      
    # Port exposure analysis
    port_exposure:
      enabled: true
      high_risk_ports: [21, 22, 23, 25, 53, 80, 135, 139, 443, 445, 993, 995, 1433, 1521, 3389, 5432]
      scoring_multiplier: 1.5
      
    # Network topology integration
    topology_integration:
      enabled: true
      bridge_node_multiplier: 1.8
      gateway_node_multiplier: 2.0
  
  # Composite Risk Calculation
  composite_scoring:
    enabled: true
    
    # Weight distribution
    weights:
      cvss_score: 0.35
      exploit_availability: 0.25
      asset_criticality: 0.25
      network_exposure: 0.15
      
    # Score normalization
    normalization:
      enabled: true
      scale: "0-10"
      precision: 1

# Alert Enrichment Configuration
alert_enrichment:
  enabled: true
  
  # Vulnerability Context Enrichment
  vulnerability_context:
    enabled: true
    
    # Context fields to add
    enrichment_fields:
      - vulnerability_description
      - cvss_scores
      - exploit_availability
      - patch_availability
      - vendor_advisories
      - related_cves
      - threat_actor_associations
      - attack_patterns
      
    # Reference sources
    reference_sources:
      - nvd
      - mitre
      - vendor_advisories
      - exploit_databases
      - threat_intelligence
  
  # Asset Context Enrichment
  asset_context:
    enabled: true
    
    # Asset information to include
    asset_fields:
      - asset_criticality
      - business_function
      - compliance_requirements
      - patch_status
      - last_scan_date
      - network_location
      - installed_software
      - open_ports
      
    # Data sources
    data_sources:
      asset_discovery: true
      cmdb: false
      vulnerability_scanners: true
  
  # Network Context Enrichment
  network_context:
    enabled: true
    
    # Network information
    network_fields:
      - network_segment
      - exposure_level
      - traffic_patterns
      - communication_peers
      - anomalous_behavior
      - related_incidents
      
    # Integration with network monitoring
    monitoring_integration:
      flow_analysis: true
      ids_alerts: true
      behavioral_analysis: true
  
  # Mitigation Recommendations
  mitigation_recommendations:
    enabled: true
    
    # Recommendation types
    recommendation_types:
      - patch_information
      - workaround_procedures
      - network_segmentation
      - access_controls
      - monitoring_enhancements
      
    # Prioritization factors
    prioritization:
      exploit_availability: 3.0
      asset_criticality: 2.5
      network_exposure: 2.0
      business_impact: 2.0

# Correlation Engine Configuration
correlation_engine:
  enabled: true
  
  # Correlation Rules
  correlation_rules:
    enabled: true
    
    # Vulnerability clustering
    vulnerability_clustering:
      enabled: true
      cluster_by:
        - cve_family
        - affected_software
        - attack_vector
        - vulnerability_type
      similarity_threshold: 0.7
      
    # Asset-based correlation
    asset_correlation:
      enabled: true
      correlation_factors:
        - same_asset
        - same_subnet
        - same_application
        - same_vendor
      time_window: 86400  # 24 hours
      
    # Attack chain correlation
    attack_chain:
      enabled: true
      chain_detection:
        initial_access: true
        privilege_escalation: true
        lateral_movement: true
        persistence: true
        data_exfiltration: true
      confidence_threshold: 0.6
      
  # Temporal Correlation
  temporal_correlation:
    enabled: true
    
    # Time-based analysis
    time_windows:
      immediate: 300      # 5 minutes
      short_term: 3600    # 1 hour
      medium_term: 86400  # 24 hours
      long_term: 604800   # 7 days
      
    # Pattern detection
    pattern_detection:
      burst_detection: true
      periodic_patterns: true
      trend_analysis: true
      anomaly_detection: true
  
  # Graph-based Analysis
  graph_analysis:
    enabled: true
    
    # Graph construction
    graph_construction:
      nodes: ["assets", "vulnerabilities", "threats", "exploits"]
      edges: ["affects", "exploits", "related_to", "leads_to"]
      
    # Analysis algorithms
    algorithms:
      centrality_analysis: true
      community_detection: true
      path_analysis: true
      influence_propagation: true
      
    # Visualization
    visualization:
      enabled: false  # Requires web interface
      layout_algorithm: "force_directed"
      export_formats: ["graphml", "gexf"]

# Database Configuration
database:
  # Primary correlation database
  correlation_db:
    type: "sqlite"
    path: "/var/lib/nsm/vulnerability_correlation.db"
    connection_pool_size: 20
    timeout: 30
    
    # Performance optimization
    optimization:
      enable_wal_mode: true
      enable_foreign_keys: true
      cache_size_mb: 512
      temp_store: "memory"
      
    # Backup settings
    backup:
      enabled: true
      frequency: "daily"
      retention_days: 30
      backup_path: "/var/backups/nsm/vulnerability_correlation"
      compression: true
  
  # Vulnerability data cache
  vulnerability_cache:
    type: "redis"
    connection:
      host: "redis-nsm.isectech.local"
      port: 6379
      db: 7  # Dedicated DB for vulnerability correlation
      password: "${REDIS_PASSWORD}"
      
    # Cache settings
    settings:
      default_ttl: 86400  # 24 hours
      max_memory_mb: 1024
      eviction_policy: "allkeys-lru"
      
    # Key patterns
    key_patterns:
      vulnerabilities: "vuln:{cve_id}"
      assets: "asset:{asset_id}"
      correlations: "corr:{correlation_id}"
      scores: "score:{asset_id}:{cve_id}"

# Integration Configuration
integrations:
  # SIEM Integration
  siem:
    enabled: true
    
    # Splunk
    splunk:
      enabled: true
      host: "splunk.isectech.local"
      port: 8088
      token: "${SPLUNK_HEC_TOKEN}"
      index: "vulnerability_correlation"
      
      # Event formatting
      event_format:
        source: "vulnerability_correlation"
        sourcetype: "vulnerability_alert"
        include_context: true
        
    # Elastic Stack
    elastic:
      enabled: true
      hosts: ["elastic01.isectech.local:9200"]
      username: "${ELASTIC_USERNAME}"
      password: "${ELASTIC_PASSWORD}"
      index_pattern: "vulnerability-correlation-%Y-%m-%d"
      
      # Document mapping
      mapping:
        dynamic: false
        include_raw_data: false
        geo_ip_enabled: true
  
  # SOAR Integration
  soar:
    enabled: true
    
    # Phantom/SOAR
    phantom:
      enabled: true
      host: "phantom.isectech.local"
      api_token: "${PHANTOM_API_TOKEN}"
      
      # Playbook triggers
      playbooks:
        critical_vulnerability: "vulnerability_response_critical"
        exploit_available: "exploit_mitigation"
        asset_compromise: "incident_response"
        
    # Custom SOAR
    custom_soar:
      enabled: false
      api_url: "https://soar.isectech.local/api/v1"
      api_key: "${CUSTOM_SOAR_API_KEY}"
  
  # Ticketing Integration
  ticketing:
    enabled: true
    
    # ServiceNow
    servicenow:
      enabled: false
      instance_url: "https://isectech.service-now.com"
      username: "${SERVICENOW_USERNAME}"
      password: "${SERVICENOW_PASSWORD}"
      
    # Jira
    jira:
      enabled: true
      server_url: "https://jira.isectech.local"
      username: "${JIRA_USERNAME}"
      api_token: "${JIRA_API_TOKEN}"
      project_key: "VULN"
      
      # Issue creation
      issue_creation:
        auto_create: true
        priority_mapping:
          critical: "Critical"
          high: "High"
          medium: "Medium"
          low: "Low"

# Performance Configuration
performance:
  # Resource limits
  max_memory_usage_gb: 6
  max_cpu_cores: 4
  max_concurrent_correlations: 50
  
  # Processing optimization
  processing:
    batch_size: 100
    parallel_processing: true
    worker_processes: 4
    queue_size: 10000
    
  # Caching strategy
  caching:
    enabled: true
    cache_size_mb: 1024
    
    # Cache types
    vulnerability_cache_ttl: 86400  # 24 hours
    asset_cache_ttl: 3600          # 1 hour
    correlation_cache_ttl: 7200    # 2 hours
    
  # Database optimization
  database_optimization:
    connection_pooling: true
    query_optimization: true
    index_maintenance: true
    vacuum_frequency: 86400  # Daily

# Monitoring Configuration
monitoring:
  # Health monitoring
  health_monitoring:
    enabled: true
    check_interval: 60  # seconds
    
    # Health checks
    checks:
      - name: "database_connectivity"
        type: "database"
        timeout: 10
        
      - name: "redis_connectivity"
        type: "redis"
        timeout: 5
        
      - name: "vulnerability_scanner_connectivity"
        type: "external_service"
        services: ["nessus", "openvas"]
        timeout: 15
        
      - name: "threat_intelligence_feeds"
        type: "external_api"
        apis: ["nvd", "misp"]
        timeout: 20
  
  # Performance monitoring
  performance_monitoring:
    enabled: true
    
    # Metrics collection
    metrics:
      - vulnerabilities_processed
      - correlations_generated
      - alerts_enriched
      - processing_latency
      - error_rate
      - cache_hit_rate
      
    # Prometheus integration
    prometheus:
      enabled: true
      port: 9093
      metrics_path: "/metrics"
  
  # Alerting
  alerting:
    enabled: true
    
    # Alert conditions
    conditions:
      - name: "high_processing_latency"
        metric: "processing_latency"
        threshold: 300  # seconds
        severity: "warning"
        
      - name: "correlation_failure_rate"
        metric: "correlation_failure_rate"
        threshold: 10  # percent
        severity: "critical"
        
      - name: "vulnerability_scan_lag"
        metric: "last_scan_age"
        threshold: 86400  # 24 hours
        severity: "warning"
    
    # Alert destinations
    destinations:
      - type: "webhook"
        url: "http://alertmanager.isectech.local:9093/api/v1/alerts"
        
      - type: "email"
        smtp_server: "smtp.isectech.local"
        recipients: ["security@isectech.local"]

# Security Configuration
security:
  # API security
  api_security:
    enabled: true
    authentication_required: true
    api_key_header: "X-API-Key"
    
    # Rate limiting
    rate_limiting:
      enabled: true
      requests_per_minute: 1000
      burst_size: 100
  
  # Data protection
  data_protection:
    # Encryption
    encryption:
      encrypt_database: true
      encryption_key_file: "/etc/nsm/vulnerability_correlation_encryption.key"
      
    # Privacy
    privacy:
      anonymize_internal_ips: false  # Keep for correlation
      hash_hostnames: false
      data_retention_days: 365
      
    # Access control
    access_control:
      rbac_enabled: true
      rbac_config: "/etc/nsm/rbac_vulnerability_correlation.yaml"

# Logging Configuration
logging:
  # Log levels
  level: "INFO"
  
  # Log destinations
  destinations:
    - type: "file"
      path: "/var/log/nsm/vulnerability_correlation.log"
      rotation: "daily"
      retention_days: 30
      
    - type: "syslog"
      facility: "local4"
      server: "syslog.isectech.local:514"
      
  # Log formats
  format: "json"
  include_timestamps: true
  include_source_info: true

# Development and Testing
development:
  # Debug settings
  debug_mode: false
  verbose_logging: false
  
  # Testing
  test_mode: false
  synthetic_vulnerabilities: false
  
  # Experimental features
  experimental:
    enable_ai_correlation: false
    enable_predictive_scoring: false
    enable_behavioral_correlation: true