apiVersion: v1
kind: ConfigMap
metadata:
  name: deception-config
  namespace: deception
  labels:
    app: deception-infrastructure
data:
  # SIEM Integration Settings
  siem.endpoint: "https://elasticsearch.monitoring.svc.cluster.local:9200"
  siem.index.pattern: "deception-events"
  siem.batch.size: "100"
  siem.flush.interval: "30s"
  
  # SOAR Integration Settings  
  soar.endpoint: "https://soar.security.isectech.com/api/v1"
  soar.playbook.high.confidence: "deception-high-confidence-alert"
  soar.playbook.medium.confidence: "deception-medium-confidence-alert"
  soar.timeout: "30s"
  
  # Honeypot Configuration
  honeypot.api.image: "isectech/api-honeypot:v1.0.0"
  honeypot.web.image: "isectech/web-honeypot:v1.0.0"
  honeypot.ssh.image: "isectech/ssh-honeypot:v1.0.0"
  honeypot.database.mysql.image: "isectech/mysql-honeypot:v1.0.0"
  honeypot.database.postgres.image: "isectech/postgres-honeypot:v1.0.0"
  honeypot.database.mongodb.image: "isectech/mongodb-honeypot:v1.0.0"
  
  # Token Management
  token.api.prefix: "ct_isec_"
  token.dns.domain: "canary.isectech.internal"
  token.generation.batch.size: "50"
  token.distribution.enabled: "true"
  
  # Alert Thresholds
  alert.confidence.high: "0.8"
  alert.confidence.medium: "0.5"
  alert.confidence.low: "0.2"
  alert.rate.limit: "100"
  
  # Monitoring Configuration
  monitoring.metrics.enabled: "true"
  monitoring.health.check.interval: "30s"
  monitoring.log.level: "info"
  monitoring.retention.days: "90"
  
  # Security Settings
  security.encryption.algorithm: "AES-256-GCM"
  security.token.rotation.interval: "24h"
  security.session.timeout: "30m"
  security.max.failed.attempts: "5"
  
  # Application Configuration
  app.config.yaml: |
    deception:
      honeypots:
        api:
          enabled: true
          replicas: 3
          ports: [8080, 8443]
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
        web:
          enabled: true
          replicas: 2
          ports: [80, 443]
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
        ssh:
          enabled: true
          replicas: 2
          ports: [22]
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "512Mi"
        database:
          mysql:
            enabled: true
            replicas: 1
            ports: [3306]
          postgres:
            enabled: true
            replicas: 1
            ports: [5432]
          mongodb:
            enabled: true
            replicas: 1
            ports: [27017]
      canary_tokens:
        file_tokens:
          enabled: true
          types: ["config", "env", "json", "yaml"]
          distribution_paths: ["/etc/app", "/var/config", "/opt/secrets"]
        database_tokens:
          enabled: true
          types: ["user_records", "api_keys", "session_tokens"]
        network_tokens:
          enabled: true
          types: ["dns", "url", "email"]
          dns_domain: "canary.isectech.internal"
      alerting:
        channels:
          siem:
            enabled: true
            priority: "high"
          soar:
            enabled: true
            priority: "high" 
          slack:
            enabled: true
            priority: "medium"
          email:
            enabled: true
            priority: "low"
        rules:
          - name: "High Confidence Interaction"
            condition: "confidence > 0.8"
            actions: ["siem", "soar", "slack"]
            severity: "critical"
          - name: "Medium Confidence Interaction"  
            condition: "confidence > 0.5 && confidence <= 0.8"
            actions: ["siem", "slack"]
            severity: "high"
          - name: "Low Confidence Interaction"
            condition: "confidence > 0.2 && confidence <= 0.5"
            actions: ["siem"]
            severity: "medium"
      analytics:
        behavioral_analysis:
          enabled: true
          ml_models: ["anomaly_detection", "pattern_matching"]
        threat_intelligence:
          enabled: true
          feeds: ["misp", "otx", "internal"]
        forensics:
          enabled: true
          capture_full_sessions: true
          artifact_retention: "30d"